# Total players needed for the competition to start
total_players: 8

# Player configurations
players:
  - id: 1
    name: Joey
    defense: 8
  - id: 2
    name: Nick
    defense: 8
  - id: 3
    name: Russel
    defense: 7
  - id: 4
    name: Vivek
    defense: 7
  - id: 5
    name: Pritam
    defense: 6
  - id: 6
    name: Amit
    defense: 6
  - id: 7
    name: Chandler
    defense: 5
  - id: 8
    name: Colwin
    defense: 5

# Host and Port to run the Referee server on
referee.server.host: localhost
referee.server.port: 5000

# Starting Port sequence on which the player processes will run
player.server.start_port: 5001

# Redis Connection configurations
redis.host: localhost
redis.port: 6379
redis.db: 0

competition.cache_key: competition
games.cache_key_prefix: ping_pong_game
player.cache_key_prefix: player
